### ISSUE TITLE
OpenID4VP metadata parameter presentation_definition_supported

### ISSUE THREAD

**Issue by peppelinux** [openid/federation-wallet#12]
OpenID4VP metadata parameter presentation_definition_supported was introduced to ensure presentation definitions within metadata are secured by a trusted third party, preventing over-asking by verifiers. A similar mechanism will be identified for the new query language being adopted.

The openid4vp related issue is the one below:
https://github.com/openid/OpenID4VP/issues/189

**Comment by jogu** [comment]
As per my response on https://github.com/openid/OpenID4VP/issues/189#issuecomment-2296992571 this proposal doesn't seem to work for the browser API, and I can't come up with a variant of it that does. I think this probably needs to be rethought about from first principles.

**Comment by peppelinux** [comment]
This issue is going to be closed since there is a growing interest in using trust marks for enabling the data the RPs are authorized to request
